/* tslint:disable */
/* eslint-disable */
/*
Test Automation (No submodules)

SDKs (no submodules) to test automation workflows.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/greetings-api';

