/*
Test Automation (No submodules)

SDKs (no submodules) to test automation workflows.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface HelloResponse
 */
export interface HelloResponse {
    /**
     * The greeting message
     * @type {string}
     * @memberof HelloResponse
     */
    'message': string;
}

